
---
title: "Class2_Cont - Control Structures and Functions in R"
author: "IGIRUKWAYO Ildephonse"
date: "2025-10-05"
output:
  html_document:
    toc: true
    toc_float: true
  pdf_document: default
---

```{r setup, include=TRUE, echo=TRUE}
# Class 2 - Control Structures and Functions in R
# Dr. Pacifique
# 2025-10-05
```

## Control Structures in R

Control structures in R allow you to control the flow of execution of your code.

### if and else

```{r}
if (condition) {
  # do something
}

if (condition) {
  # do something
} else {
  # do something else
}

if (condition1) {
  # do something
} else if (condition2) {
  # do something different
} else {
  # do something else
}
```

### Functions

```{r}
f <- function(x) x^2
formals(f)
body(f)
environment(f)
```

### ifelse Example

```{r}
pvalues <- c(.867, 0.0054, 0.0018, 0.1572, 0.0183, 0.5386)
results <- ifelse(pvalues < 0.05, "Significant", "Not significant")
results
```

### Random Example

```{r}
x <- runif(1, 0, 10)
if (x > 3) {
  y <- 10
} else {
  y <- 0
}
y <- if (x > 3) { 10 } else { 0 }
```

## For Loops

```{r}
for (i in 1:10) {
  print(i)
}

x <- c("a", "b", "c", "d")
for (i in 1:5) {
  print(x[i])
}

for (i in 1:5) print(1:i)
for (i in 5:1) print(1:i)
```

## While Loops

```{r}
count <- 1
while (count < 10) {
  print(count)
  count <- count + 1
}

z <- 5
set.seed(1)
while (z >= 3 && z <= 10) {
  coin <- rbinom(1, 1, 0.5)
  if (coin == 1) {
    z <- z + 1
  } else {
    z <- z - 1
  }
}
print(z)
```

## next and break

```{r}
for (i in 1:100) {
  print(1:i)
  if (i > 20) {
    break
  }
}
```

## Functions

```{r}
f1 <- function(x) {
  result <- x^2 + 2
  return(result)
}

f2 <- function(x, y) {
  result <- x^2 + y^2 - 4
  return(result)
}

f <- function(x, y) {
  result <- x + (2 * y) + 3
  return(result)
}

f(2, 3)
args(f)
```

## Matrices and apply()

```{r}
a <- 4
sqrt(a)

b <- c(1, 243, 5.754, 2.987)
round(b)

c <- matrix(runif(12), nrow = 3)
c
log(c)
mean(c)
apply(c, 1, mean)
apply(c, 2, mean)
```

## lapply and sapply

```{r}
fix_missing <- function(x) {
  x[x == -99] <- NA
  x
}

function1 <- function(x) {
  x^2
}

curve(function1, -4, 4)
```

## Titanic Data Example

```{r}
str(Titanic)
apply(Titanic, c(1, 2), sum)
apply(Titanic, c(1, 4), sum)
ftable(apply(Titanic, c(1, 4, 2), sum)[3:4,,])
```

## Student Performance Example

```{r}
Student <- c("John ncuti", "Angela bakame", "Bruce wizeye",
             "Alexis aganze", "claude Rukundo", "Joel Kagabo", "Mary ineza")
Math <- c(600, 412, 358, 495, 512, 410, 522)
Science <- c(95, 99, 80, 82, 75, 89, 77)
English <- c(25, 22, 18, 20, 29, 30, 27)

roster <- data.frame(Student, Math, Science, English, stringsAsFactors = FALSE)
z <- scale(roster[, 2:4])
score <- apply(z, 1, mean)
roster <- cbind(roster, score)

y <- quantile(score, c(.8, .6, .4, .2))
roster$grade[score >= y[1]] <- "A"
roster$grade[score < y[1] & score >= y[2]] <- "B"
roster$grade[score < y[2] & score >= y[3]] <- "C"
roster$grade[score < y[3] & score >= y[4]] <- "D"
roster$grade[score < y[4]] <- "F"
roster
```

## Aggregation and Reshaping

```{r}
cars <- mtcars[1:5, 1:4]
cars
t(cars)

attach(mtcars)
aggdata <- aggregate(mtcars, by = list(cyl, gear), FUN = mean, na.rm = TRUE)

library(reshape2)
id <- c(1, 1, 2, 2)
time <- c(1, 2, 1, 2)
x1 <- c(5, 3, 6, 2)
x2 <- c(6, 5, 1, 4)
mydata <- data.frame(id, time, x1, x2)
mydata
```
